import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const config=window.NEXA_SUPABASE||{},supabase=createClient(config.url,config.publishableKey),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const message=q('#message'),state={};
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const short=(v='')=>String(v).length>20?`${String(v).slice(0,10)}…${String(v).slice(-7)}`:String(v);
const pill=v=>`<span class="pill ${['blocked','rejected','restricted','failed','emergency_stopped','prohibited'].includes(v)?'danger':['pending','review','under_review','submitted','provider_pending','paused'].includes(v)?'warn':''}">${esc(v||'—')}</span>`;
const units=v=>{const t=String(v||0),n=t.startsWith('-'),[w,f='']=(n?t.slice(1):t).split('.'),x=BigInt(w||0)*10n**18n+BigInt(f.padEnd(18,'0').slice(0,18)||0);return n?-x:x};
const decimal=x=>{const n=x<0n,v=n?-x:x,w=v/10n**18n,f=(v%10n**18n).toString().padStart(18,'0').replace(/0+$/,'').slice(0,8);return`${n?'-':''}${w}${f?'.'+f:''}`};
const show=(text,error=false)=>{message.style.display='block';message.style.color=error?'#ffb1ba':'var(--aqua)';message.textContent=text;message.scrollIntoView({behavior:'smooth',block:'nearest'});if(!error)setTimeout(()=>message.style.display='none',8000)};
const val=id=>q(id)?.value?.trim(),num=id=>val(id)===''||val(id)==null?null:Number(val(id));
const customerName=id=>state.directoryById?.[id]?.display_name||short(id),accountFor=id=>state.accounts?.find(a=>a.customer_id===id);
const csv=(name,rows)=>{if(!rows.length)return show('Nothing to export.',true);const keys=Object.keys(rows[0]),cell=v=>`"${String(v??'').replace(/"/g,'""')}"`,blob=new Blob([[keys.join(','),...rows.map(r=>keys.map(k=>cell(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(','))].join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)};
async function rpc(name,args,success){const {error}=await supabase.rpc(name,args);if(error)return show(error.message,true);show(success);await load()}

const {data:{user}}=await supabase.auth.getUser();
if(!user)location.replace('admin-login.html');
else{
 const {data:me,error:meError}=await supabase.from('profiles').select('display_name,role').eq('id',user.id).single();
 if(meError||!['operator','compliance_admin'].includes(me?.role)){location.replace(`dashboard.html?admin_error=${encodeURIComponent(meError?.message||'staff_role_required')}`)}
 else{
 q('#admin-name').textContent=`${me.display_name||user.email} · ${me.role}`;
 qa('#admin-nav button').forEach(b=>b.onclick=()=>{qa('#admin-nav button').forEach(x=>x.classList.toggle('active',x===b));qa('.admin-view').forEach(v=>v.classList.toggle('active',v.id===`view-${b.dataset.view}`));location.hash=b.dataset.view});
 if(location.hash){q(`[data-view="${location.hash.slice(1)}"]`)?.click()}

 async function load(){
  q('#load-state').textContent='Refreshing';
  const calls={directory:supabase.rpc('admin_customer_directory'),accounts:supabase.from('customer_accounts').select('*').order('created_at',{ascending:false}),compliance:supabase.from('customer_compliance').select('*'),consents:supabase.from('user_consents').select('*'),instructions:supabase.from('deposit_instructions').select('*').order('created_at',{ascending:false}),funding:supabase.from('funding_requests').select('*').order('submitted_at',{ascending:false}),withdrawals:supabase.from('withdrawal_requests').select('*').order('submitted_at',{ascending:false}),walletRequests:supabase.from('wallet_connection_requests').select('*').order('submitted_at',{ascending:false}),wallets:supabase.from('wallet_connections').select('*').order('created_at',{ascending:false}),ledger:supabase.from('portfolio_ledger').select('*').order('created_at',{ascending:false}),strategies:supabase.from('strategy_assignments').select('*').order('created_at',{ascending:false}),trades:supabase.from('trade_requests').select('*').order('created_at',{ascending:false}),fees:supabase.from('fee_schedules').select('*'),controls:supabase.from('system_controls').select('*').eq('id',true).maybeSingle(),audit:supabase.from('admin_audit_log').select('*').order('created_at',{ascending:false}).limit(500)};
  const keys=Object.keys(calls),results=await Promise.all(Object.values(calls));
  const failures=results.map((r,i)=>r.error?(keys[i]+': '+r.error.message):null).filter(Boolean);
  keys.forEach((k,i)=>state[k]=results[i].error?(k==='controls'?null:[]):results[i].data);
  const fullDirectory=Array.isArray(state.directory)?state.directory:[];
  state.directoryById=Object.fromEntries(fullDirectory.map(x=>[x.customer_id,x]));
  state.directory=fullDirectory.filter(x=>x.role==='customer');
  state.accountById=Object.fromEntries(state.accounts.map(x=>[x.id,x]));state.instructionById=Object.fromEntries(state.instructions.map(x=>[x.id,x]));
  render();q('#load-state').textContent=failures.length?'Partial load':'Current';
  if(failures.length)show('Supabase failed modules — '+failures.join(' | ')+'. Run migration 012_repair_admin_console_access.sql, then refresh.',true);
 }

 function options(selected=''){return state.directory.map(c=>`<option value="${c.customer_id}" ${c.customer_id===selected?'selected':''}>${esc(c.display_name)} · ${esc(c.email)}</option>`).join('')}
 function render(){
  qa('#deposit-customer,#adjustment-customer,#strategy-customer,#trade-customer,#fee-customer,#compliance-customer').forEach(s=>{const current=s.value;s.innerHTML=options(current)});
  const pendingDeposits=state.funding.filter(x=>['submitted','under_review'].includes(x.status)),pendingWithdrawals=state.withdrawals.filter(x=>['submitted','under_review'].includes(x.status)),pendingTrades=state.trades.filter(x=>x.status==='submitted');
  q('#metric-customers').textContent=state.directory.length;q('#metric-restricted').textContent=state.accounts.filter(x=>x.status==='restricted').length;q('#metric-deposits').textContent=pendingDeposits.length;q('#metric-withdrawals').textContent=pendingWithdrawals.length;q('#metric-trades').textContent=pendingTrades.length;
  const control=state.controls||{};q('#bot-status').value=control.bot_status||'paused';q('#maintenance').checked=!!control.maintenance_mode;q('#system-reason').value=control.reason||'';q('#audit-bot-state').textContent=control.bot_status||'—';q('#audit-maintenance').textContent=control.maintenance_mode?'ON':'OFF';q('#audit-count').textContent=state.audit.length;
  q('#attention-list').innerHTML=`<div class="strategy"><div class="strategy-row"><span>Deposits awaiting review</span><b>${pendingDeposits.length}</b></div><div class="strategy-row"><span>Withdrawals awaiting review</span><b>${pendingWithdrawals.length}</b></div><div class="strategy-row"><span>Trades awaiting independent approval</span><b>${pendingTrades.length}</b></div><div class="strategy-row"><span>Sanctions/risk reviews</span><b>${state.compliance.filter(x=>['review','blocked'].includes(x.sanctions_status)||['high','prohibited'].includes(x.risk_level)).length}</b></div></div>`;
  renderCustomers();renderPortfolio();renderDeposits();renderWithdrawals();renderTrading();renderWallets();renderFees();renderCompliance();renderAudit();bindActions();
 }

 function renderCustomers(){const term=(q('#customer-search').value||'').toLowerCase();q('#customers-table').innerHTML=state.directory.filter(c=>`${c.display_name} ${c.email} ${c.mobile_number||''} ${c.customer_id}`.toLowerCase().includes(term)).map(c=>{const a=accountFor(c.customer_id),co=state.compliance.find(x=>x.customer_id===c.customer_id),cons=state.consents.filter(x=>x.customer_id===c.customer_id).length;return`<tr><td><b>${esc(c.display_name)}</b></td><td>${esc(c.email)}<br>${esc(c.mobile_number||'No mobile recorded')}<br><span class="mono" title="${c.customer_id}">${short(c.customer_id)}</span></td><td>${new Date(c.created_at).toLocaleDateString()}</td><td>${pill(a?.status)}</td><td>${pill(co?.kyc_status||'not_started')} ${pill(co?.risk_level||'unrated')}</td><td>${cons} records</td><td>${esc(a?.custody_provider_account_ref||'Not assigned')}</td><td><div class="actions"><button class="button secondary" data-account-status="active" data-customer="${c.customer_id}">Activate</button><button class="button secondary" data-account-status="restricted" data-customer="${c.customer_id}">Restrict</button><button class="button secondary" data-account-status="closed" data-customer="${c.customer_id}">Archive</button><button class="button danger" data-delete="${c.customer_id}" data-name="${esc(c.display_name)}">Delete unused test</button></div></td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No customers match.</td></tr>'}

 function totalsFor(accountId){const out={};state.ledger.filter(x=>x.account_id===accountId).forEach(x=>out[x.asset_symbol]=(out[x.asset_symbol]||0n)+units(x.quantity));return out}
 function renderPortfolio(){q('#portfolio-table').innerHTML=state.accounts.map(a=>{const totals=totalsFor(a.id),balances=Object.entries(totals).map(([asset,x])=>`${decimal(x)} ${asset}`).join(' · ')||'No balance',deposits=state.ledger.filter(x=>x.account_id===a.id&&x.entry_type==='deposit').length,withdrawals=state.ledger.filter(x=>x.account_id===a.id&&x.entry_type==='withdrawal').length,fees=state.ledger.filter(x=>x.account_id===a.id&&x.entry_type==='fee').reduce((s,x)=>s+units(x.quantity),0n),last=state.ledger.find(x=>x.account_id===a.id);return`<tr><td>${esc(customerName(a.customer_id))}</td><td><b>${balances}</b></td><td>${deposits}</td><td>${withdrawals}</td><td>${decimal(fees)}</td><td>${last?new Date(last.created_at).toLocaleString():'—'}</td></tr>`}).join('');q('#ledger-table').innerHTML=state.ledger.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(customerName(state.accountById[x.account_id]?.customer_id))}</td><td>${esc(x.asset_symbol)}</td><td>${esc(x.quantity)}</td><td>${pill(x.entry_type)}</td><td class="mono">${esc(x.external_reference||'—')}</td><td class="mono">${short(x.recorded_by||'system')}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No ledger entries.</td></tr>'}

 function renderDeposits(){q('#deposit-instructions-table').innerHTML=state.instructions.map(i=>`<tr><td>${esc(customerName(state.accountById[i.account_id]?.customer_id))}</td><td>${esc(i.asset_symbol)} · ${i.chain_id}</td><td class="mono" title="${esc(i.deposit_address)}">${short(i.deposit_address)}</td><td>${esc(i.provider_reference)}</td><td>${pill(i.status)}</td><td>${i.status==='active'?`<button class="button secondary" data-disable-instruction="${i.id}">Disable / rotate</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No instructions.</td></tr>';q('#funding-table').innerHTML=state.funding.map(f=>{const i=state.instructionById[f.instruction_id]||{},pending=['submitted','under_review'].includes(f.status);return`<tr><td>${esc(customerName(f.customer_id))}</td><td class="mono" title="${esc(f.transaction_hash)}">${short(f.transaction_hash)}<br>${esc(i.asset_symbol||'')} · chain ${i.chain_id??'?'}</td><td>${esc(f.declared_amount)}</td><td><input data-funded-qty="${f.id}" type="number" step="any" value="${esc(f.declared_amount)}" ${pending?'':'disabled'}></td><td><input data-confirms="${f.id}" type="number" min="1" value="1" ${pending?'':'disabled'}></td><td><input data-verify-ref="${f.id}" placeholder="provider/explorer ID" ${pending?'':'disabled'}></td><td>${pill(f.status)} ${pending?`<div class="actions"><button class="button" data-funding="${f.id}" data-decision="approved">Approve</button><button class="button secondary" data-funding="${f.id}" data-decision="rejected">Reject</button></div>`:''}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No deposit submissions.</td></tr>'}

 function renderWithdrawals(){q('#withdrawals-table').innerHTML=state.withdrawals.map(w=>`<tr><td>${esc(customerName(w.customer_id))}</td><td>${esc(w.quantity)} ${esc(w.asset_symbol)}<br><span class="mono">${w.chain_id===0?'Bitcoin mainnet':'chain '+esc(w.chain_id||'—')}</span></td><td class="mono" title="${esc(w.destination_address)}">${short(w.destination_address)}</td><td>${pill(w.status)}</td><td>${w.reviewed_at?new Date(w.reviewed_at).toLocaleString():'—'}</td><td>${['submitted','under_review'].includes(w.status)?`<div class="actions"><button class="button secondary" data-withdrawal="${w.id}" data-withdrawal-decision="under_review">Freeze/review</button><button class="button" data-withdrawal="${w.id}" data-withdrawal-decision="approved">Approve provider request</button><button class="button danger" data-withdrawal="${w.id}" data-withdrawal-decision="rejected">Reject</button></div>`:['approved','processing'].includes(w.status)?`<div class="actions"><input data-withdrawal-tx="${w.id}" placeholder="Genuine provider transaction ID / hash"><button class="button secondary" data-withdrawal-broadcast="${w.id}">Mark broadcast</button><input data-withdrawal-confirms="${w.id}" type="number" min="1" value="1" style="width:70px" title="Confirmations"><button class="button" data-withdrawal-complete="${w.id}">Confirm settlement & deduct ledger</button><button class="button danger" data-withdrawal-cancel="${w.id}">Cancel & release reservation</button></div>`:w.status==='broadcast'?`<div class="actions"><span class="mono">${esc(w.provider_transaction_id||'Transaction pending')}</span><input data-withdrawal-confirms="${w.id}" type="number" min="1" value="1" style="width:70px"><button class="button" data-withdrawal-complete="${w.id}">Confirm settlement & deduct ledger</button></div>`:w.status==='completed'?`Completed · ${esc(w.provider_transaction_id||'provider receipt recorded')}`:'Provider execution / receipt pending'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No withdrawal requests.</td></tr>'}

 function renderTrading(){q('#strategies-table').innerHTML=state.strategies.map(s=>`<tr><td>${esc(customerName(s.customer_id))}</td><td>${esc(s.strategy_name)}</td><td>${esc((s.allowed_assets||[]).join(', '))}</td><td>Position ${esc(s.max_position)}<br>Daily ${esc(s.daily_trade_limit)}<br>DD ${esc(s.max_drawdown_pct)}%</td><td>${pill(s.status)}</td><td><div class="actions"><button class="button secondary" data-strategy="${s.id}" data-strategy-status="${s.status==='active'?'paused':'active'}">${s.status==='active'?'Pause':'Activate'}</button><button class="button danger" data-strategy="${s.id}" data-strategy-status="revoked">Revoke</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No strategies.</td></tr>';q('#trade-strategy').innerHTML='<option value="">None</option>'+state.strategies.filter(x=>x.status==='active').map(x=>`<option value="${x.id}">${esc(customerName(x.customer_id))} · ${esc(x.strategy_name)}</option>`).join('');q('#trades-table').innerHTML=state.trades.map(t=>`<tr><td>${esc(customerName(t.customer_id))}</td><td>${esc(t.side)} ${esc(t.sell_asset)}/${esc(t.buy_asset)}</td><td>${esc(t.quantity)}</td><td>Limit ${esc(t.limit_price||'market')}<br>Slip ${esc(t.max_slippage_pct)}%<br>Fee ${esc(t.estimated_fee||0)}</td><td class="mono">${short(t.requested_by)}</td><td>${pill(t.status)}</td><td>${t.status==='submitted'?`<div class="actions"><button class="button" data-trade="${t.id}" data-trade-decision="approved">Approve</button><button class="button danger" data-trade="${t.id}" data-trade-decision="rejected">Reject</button></div>`:t.status==='provider_pending'?'Awaiting provider integration':esc(t.rejection_reason||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No trade proposals.</td></tr>'}

 function renderWallets(){const reqByKey=Object.fromEntries(state.walletRequests.map(x=>[`${x.customer_id}:${x.wallet_address.toLowerCase()}:${x.chain_id}`,x]));const rows=[...state.wallets.map(w=>({...w,request:reqByKey[`${w.customer_id}:${w.wallet_address.toLowerCase()}:${w.chain_id}`]})),...state.walletRequests.filter(r=>!state.wallets.some(w=>w.customer_id===r.customer_id&&w.wallet_address.toLowerCase()===r.wallet_address.toLowerCase()&&w.chain_id===r.chain_id)).map(r=>({customer_id:r.customer_id,wallet_address:r.wallet_address,chain_id:r.chain_id,request:r,permission_summary:{}}))];q('#wallets-table').innerHTML=rows.map(w=>{const r=w.request,status=r?.status||(w.revoked_at?'revoked':'verified');return`<tr><td>${esc(customerName(w.customer_id))}</td><td class="mono" title="${esc(w.wallet_address)}">${short(w.wallet_address)}</td><td>${w.chain_id}</td><td>${pill(status)}</td><td class="mono">${esc(JSON.stringify(w.permission_summary||{}))}</td><td>${r?.verified_at?new Date(r.verified_at).toLocaleString():'—'}<br>${w.revoked_at?'Revoked '+new Date(w.revoked_at).toLocaleString():''}</td><td><div class="actions">${status==='submitted'?`<button class="button" data-wallet-review="${r.id}" data-wallet-decision="verified">Verify</button><button class="button danger" data-wallet-review="${r.id}" data-wallet-decision="rejected">Reject</button>`:''}${status==='verified'&&!w.revoked_at?`<button class="button danger" data-wallet-revoke="${w.customer_id}" data-address="${w.wallet_address}" data-chain="${w.chain_id}">Revoke delegated access</button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No connected wallets.</td></tr>'}

 function renderFees(){q('#fees-table').innerHTML=state.fees.map(f=>`<tr><td>${esc(customerName(f.customer_id))}</td><td>${esc(f.management_fee_pct)}%</td><td>${esc(f.performance_fee_pct)}%</td><td>${esc(f.high_water_mark)}</td><td>${esc(f.calculation_period)}</td><td>${esc(f.collection_method)}</td><td>${pill(f.status)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No fee schedules.</td></tr>'}
 function renderCompliance(){q('#compliance-table').innerHTML=state.directory.map(c=>{const x=state.compliance.find(y=>y.customer_id===c.customer_id)||{};return`<tr><td>${esc(c.display_name)}</td><td>${pill(x.kyc_status||'not_started')}</td><td>${pill(x.sanctions_status||'not_screened')}</td><td>${esc(x.country_code||'—')}</td><td>${pill(x.source_of_funds_status||'not_requested')}</td><td>${pill(x.risk_level||'unrated')} ${x.wallet_risk_score??'—'}</td><td>Deposit ${esc(x.deposit_limit??'—')}<br>Withdrawal ${esc(x.withdrawal_limit??'—')}</td><td>${x.reviewed_at?new Date(x.reviewed_at).toLocaleString():'—'}</td></tr>`}).join('')}
 function renderAudit(){q('#audit-table').innerHTML=state.audit.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString()}</td><td class="mono">${short(a.actor_id)}</td><td>${esc(a.action)}</td><td>${esc(a.entity_type)}</td><td class="mono">${short(a.entity_id)}</td><td class="mono">${esc(JSON.stringify(a.details||{}))}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No audit events.</td></tr>';supabase.auth.mfa.getAuthenticatorAssuranceLevel().then(({data})=>q('#mfa-state').textContent=data?.currentLevel==='aal2'?'AAL2':'AAL1')}

 function bindActions(){
  qa('[data-account-status]').forEach(b=>b.onclick=()=>rpc('admin_set_account_status',{p_customer_id:b.dataset.customer,p_status:b.dataset.accountStatus},`Account marked ${b.dataset.accountStatus}.`));
  qa('[data-delete]').forEach(b=>b.onclick=async()=>{const id=b.dataset.delete,confirmation=prompt(`Delete unused test customer ${b.dataset.name}?\nPaste the full customer ID:\n${id}`);if(confirmation===id)await rpc('admin_delete_unused_test_customer',{p_customer_id:id,p_confirmation:id},'Unused test customer deleted.');else if(confirmation!==null)show('Customer ID did not match.',true)});
  qa('[data-disable-instruction]').forEach(b=>b.onclick=()=>rpc('admin_disable_deposit_instruction',{p_instruction_id:b.dataset.disableInstruction},'Deposit instruction disabled.'));
   qa('[data-funding]').forEach(b=>b.onclick=()=>reviewFunding(b));qa('[data-withdrawal]').forEach(b=>b.onclick=()=>reviewWithdrawal(b));qa('[data-withdrawal-broadcast]').forEach(b=>b.onclick=()=>broadcastWithdrawal(b));qa('[data-withdrawal-complete]').forEach(b=>b.onclick=()=>completeWithdrawal(b));qa('[data-withdrawal-cancel]').forEach(b=>b.onclick=()=>cancelApprovedWithdrawal(b));qa('[data-strategy]').forEach(b=>b.onclick=()=>rpc('admin_set_strategy_status',{p_strategy_id:b.dataset.strategy,p_status:b.dataset.strategyStatus},`Strategy ${b.dataset.strategyStatus}.`));qa('[data-trade]').forEach(b=>b.onclick=()=>reviewTrade(b));qa('[data-wallet-review]').forEach(b=>b.onclick=()=>rpc('admin_review_wallet_request',{p_request_id:b.dataset.walletReview,p_decision:b.dataset.walletDecision},`Wallet ${b.dataset.walletDecision}.`));qa('[data-wallet-revoke]').forEach(b=>b.onclick=()=>{const reason=prompt('Reason for revoking delegated wallet access:');if(reason)rpc('admin_revoke_wallet',{p_customer_id:b.dataset.walletRevoke,p_wallet_address:b.dataset.address,p_chain_id:Number(b.dataset.chain),p_reason:reason},'Wallet access revoked.')});
 }
 async function reviewFunding(b){const id=b.dataset.funding,decision=b.dataset.decision,qty=q(`[data-funded-qty="${id}"]`)?.value,conf=q(`[data-confirms="${id}"]`)?.value,ref=q(`[data-verify-ref="${id}"]`)?.value.trim();if(decision==='approved'&&(!qty||!ref||Number(conf)<1))return show('Verified amount, confirmations and reference are required.',true);await rpc('admin_review_funding_request',{p_request_id:id,p_decision:decision,p_verified_quantity:decision==='approved'?qty:null,p_verification_reference:decision==='approved'?ref:null,p_confirmations:decision==='approved'?Number(conf):null},`Deposit ${decision}.`)}
 async function reviewWithdrawal(b){const reason=prompt(`Reason / verification note for ${b.dataset.withdrawalDecision}:`)||'';await rpc('admin_review_withdrawal',{p_request_id:b.dataset.withdrawal,p_decision:b.dataset.withdrawalDecision,p_reason:reason},`Withdrawal ${b.dataset.withdrawalDecision}.`)}
 async function broadcastWithdrawal(b){const id=b.dataset.withdrawalBroadcast,tx=q(`[data-withdrawal-tx="${id}"]`)?.value.trim();if(!tx)return show('Enter the provider transaction ID or blockchain hash.',true);await rpc('admin_mark_withdrawal_broadcast',{p_request_id:id,p_provider_transaction_id:tx},'Withdrawal marked broadcast; ledger remains reserved until confirmation.')}
  async function completeWithdrawal(b){const id=b.dataset.withdrawalComplete,w=state.withdrawals.find(x=>x.id===id),tx=q(`[data-withdrawal-tx="${id}"]`)?.value.trim()||w?.provider_transaction_id,confirms=Number(q(`[data-withdrawal-confirms="${id}"]`)?.value||0);if(!tx||confirms<1)return show('Transaction ID and at least one confirmation are required.',true);if(!confirm(`Confirm provider settlement of ${w?.quantity} ${w?.asset_symbol}? This creates the permanent negative ledger entry.`))return;await rpc('admin_complete_withdrawal',{p_request_id:id,p_provider_transaction_id:tx,p_confirmations:confirms},'Withdrawal settled and deducted from the immutable ledger.')}
  async function cancelApprovedWithdrawal(b){const id=b.dataset.withdrawalCancel,w=state.withdrawals.find(x=>x.id===id),reason=prompt(`Why should the approved ${w?.quantity||''} ${w?.asset_symbol||''} withdrawal be cancelled?`);if(!reason)return;await rpc('admin_cancel_approved_withdrawal',{p_request_id:id,p_reason:reason},'Withdrawal cancelled; the reservation is released without changing the settled ledger.')}
 async function reviewTrade(b){const reason=b.dataset.tradeDecision==='rejected'?(prompt('Rejection reason:')||'Rejected by compliance'):'';await rpc('admin_review_trade_request',{p_trade_id:b.dataset.trade,p_decision:b.dataset.tradeDecision,p_reason:reason},`Trade ${b.dataset.tradeDecision}; provider execution remains pending.`)}

 q('#system-form').onsubmit=e=>{e.preventDefault();rpc('admin_set_system_controls',{p_bot_status:val('#bot-status'),p_maintenance:q('#maintenance').checked,p_reason:val('#system-reason')},'Global controls updated.')};
 q('#deposit-form').onsubmit=e=>{e.preventDefault();const asset=val('#deposit-asset').toUpperCase(),chain=num('#deposit-chain'),address=val('#deposit-address');if(chain===1&&(!/^0x[0-9a-fA-F]{40}$/.test(address)||asset==='BTC'))return show('Chain 1 requires an Ethereum 0x address and compatible asset.',true);rpc('admin_assign_deposit_instruction',{p_customer_id:val('#deposit-customer'),p_chain_id:chain,p_asset_symbol:asset,p_deposit_address:address,p_provider_reference:val('#deposit-reference')},'Deposit instruction assigned.')};
 q('#adjustment-form').onsubmit=e=>{e.preventDefault();rpc('admin_record_portfolio_adjustment',{p_customer_id:val('#adjustment-customer'),p_asset_symbol:val('#adjustment-asset').toUpperCase(),p_quantity:val('#adjustment-quantity'),p_reason:val('#adjustment-reason'),p_external_reference:val('#adjustment-reference')},'Immutable ledger adjustment recorded.')};
 q('#strategy-form').onsubmit=e=>{e.preventDefault();rpc('admin_save_strategy',{p_customer_id:val('#strategy-customer'),p_name:val('#strategy-name'),p_assets:val('#strategy-assets').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),p_max_position:num('#strategy-position'),p_daily_limit:num('#strategy-daily'),p_drawdown:num('#strategy-drawdown'),p_slippage:num('#strategy-slippage'),p_stop_loss:num('#strategy-stop'),p_status:val('#strategy-status'),p_expires_at:val('#strategy-expires')?new Date(val('#strategy-expires')).toISOString():null},'Strategy assigned.')};
 q('#trade-form').onsubmit=e=>{e.preventDefault();rpc('admin_create_trade_request',{p_customer_id:val('#trade-customer'),p_strategy_id:val('#trade-strategy')||null,p_side:val('#trade-side'),p_sell_asset:val('#trade-sell').toUpperCase(),p_buy_asset:val('#trade-buy').toUpperCase(),p_quantity:val('#trade-quantity'),p_limit_price:num('#trade-limit'),p_slippage:num('#trade-slippage'),p_estimated_fee:num('#trade-fee')},'Trade proposal submitted for independent approval.')};
 q('#fee-form').onsubmit=e=>{e.preventDefault();rpc('admin_save_fee_schedule',{p_customer_id:val('#fee-customer'),p_management:num('#fee-management'),p_performance:num('#fee-performance'),p_high_water:num('#fee-watermark'),p_period:val('#fee-period'),p_method:val('#fee-method'),p_status:val('#fee-status')},'Fee schedule saved.')};
 q('#compliance-form').onsubmit=e=>{e.preventDefault();rpc('admin_save_compliance',{p_customer_id:val('#compliance-customer'),p_kyc:val('#compliance-kyc'),p_sanctions:val('#compliance-sanctions'),p_country:val('#compliance-country'),p_source:val('#compliance-source'),p_risk:val('#compliance-risk'),p_wallet_score:num('#compliance-wallet-score'),p_deposit_limit:num('#compliance-deposit-limit'),p_withdrawal_limit:num('#compliance-withdrawal-limit'),p_restriction_reason:val('#compliance-restriction'),p_notes:val('#compliance-notes')},'Compliance review saved.')};
 q('#customer-search').oninput=renderCustomers;q('#export-customers').onclick=()=>csv('customers.csv',state.directory.map(c=>({...c,account_status:accountFor(c.customer_id)?.status,compliance:state.compliance.find(x=>x.customer_id===c.customer_id)||{}})));q('#export-audit').onclick=()=>csv('admin-audit.csv',state.audit);q('#refresh').onclick=load;
 q('#logout').onclick=async e=>{e.preventDefault();await supabase.auth.signOut();location.replace('admin-login.html')};
 await load();
 }
}
