import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const config=window.NEXA_SUPABASE||{},supabase=createClient(config.url,config.publishableKey),q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nav=q('#admin-nav'),main=q('.admin-main');
if(nav&&main){
 const button=document.createElement('button');button.dataset.view='health';button.textContent='System health';nav.insertBefore(button,nav.lastElementChild);
 const section=document.createElement('section');section.className='admin-view';section.id='view-health';section.innerHTML=`<div class="headline"><div><span class="kicker">Deployment verification</span><h1>System health</h1><p class="hint">Read-only checks confirm that the browser and Supabase expose the same operational contract.</p></div><button class="button secondary" id="health-refresh">Run checks</button></div><div id="health-message" class="message-bar"></div><div class="summary-grid"><div class="metric"><span class="card-label">Schema version</span><b id="health-version">—</b></div><div class="metric"><span class="card-label">Ready checks</span><b id="health-ready">—</b></div><div class="metric"><span class="card-label">Checked</span><b id="health-time">—</b></div></div><article class="card"><table class="queue"><thead><tr><th>Module</th><th>State</th><th>Required action</th></tr></thead><tbody id="health-table"><tr><td colspan="3">Run checks to verify this deployment.</td></tr></tbody></table></article><p class="notice">If the health function itself is missing, run migration 019_final_schema_reconciliation.sql in Supabase, wait a few seconds for the API cache reload, then run these checks again.</p>`;
 main.insertBefore(section,q('#view-audit'));
 button.onclick=()=>{[...nav.children].forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.admin-view').forEach(x=>x.classList.toggle('active',x===section));location.hash='health';loadHealth()};
 q('#health-refresh').onclick=loadHealth;if(location.hash==='#health')button.click();
}
async function loadHealth(){const message=q('#health-message');message.style.display='none';const{data,error}=await supabase.rpc('admin_system_health');if(error){message.style.display='block';message.style.color='#ffb1ba';message.textContent=`Database contract is incomplete: ${error.message}. Run migration 019_final_schema_reconciliation.sql, then refresh.`;q('#health-table').innerHTML='<tr><td>Schema reconciliation</td><td><span class="pill">missing</span></td><td>Run migration 019</td></tr>';return}const checks=data?.checks||[],ready=checks.filter(x=>x.ready).length;q('#health-version').textContent=esc(data?.schema_version||'unknown');q('#health-ready').textContent=`${ready} / ${checks.length}`;q('#health-time').textContent=data?.checked_at?new Date(data.checked_at).toLocaleString():'—';q('#health-table').innerHTML=checks.map(x=>`<tr><td>${esc(x.name)}</td><td><span class="pill">${x.ready?'ready':'missing'}</span></td><td>${x.ready?'None':'Apply the referenced migration'}</td></tr>`).join('');message.style.display='block';message.style.color=ready===checks.length?'var(--aqua)':'#ffb1ba';message.textContent=ready===checks.length?'All database modules used by the website are available.':'One or more required database modules are missing.'}
