(() => {
  'use strict';
  const c=window.NEXA_SITE||{},phone=c.supportPhoneE164||'+15209556559',display=c.supportPhoneDisplay||'+1 520 955 6559';
  const headLink=(rel,href,attrs={})=>{let link=document.querySelector(`link[rel="${rel}"][href="${href}"]`);if(!link){link=document.createElement('link');link.rel=rel;link.href=href;Object.entries(attrs).forEach(([key,value])=>link.setAttribute(key,value));document.head.append(link)}return link};
  document.querySelectorAll('link[rel="icon"]').forEach(icon=>icon.remove());
  headLink('icon','images/favicon_io/favicon.ico',{sizes:'any'});
  headLink('icon','images/favicon_io/favicon-32x32.png',{type:'image/png',sizes:'32x32'});
  headLink('icon','images/favicon_io/favicon-16x16.png',{type:'image/png',sizes:'16x16'});
  headLink('apple-touch-icon','images/favicon_io/apple-touch-icon.png',{sizes:'180x180'});
  headLink('manifest','images/favicon_io/site.webmanifest');
  if(document.body.classList.contains('education-theme')||document.body.classList.contains('token-theme'))headLink('stylesheet','landing-expanded.css');
  if(document.body.classList.contains('token-theme')){const sale=document.createElement('script');sale.src='token-sale-update.js';sale.defer=true;document.head.append(sale)}
  if(document.body.classList.contains('education-theme')||document.body.classList.contains('token-theme')){const reviews=document.createElement('script');reviews.type='module';reviews.src='public-reviews.js';document.head.append(reviews)}
  document.querySelectorAll('.brand-mark').forEach(mark=>{mark.setAttribute('role','img');mark.setAttribute('aria-label','NexaTrade logo');Object.assign(mark.style,{backgroundImage:'url("images/logo.png")',backgroundSize:'cover',backgroundPosition:'center',backgroundRepeat:'no-repeat',clipPath:'none',filter:'none'})});
  document.querySelectorAll('a[href^="tel:"]').forEach(link=>{link.href=`tel:${phone}`;if(!link.classList.contains('call-nav'))link.textContent=display});document.querySelectorAll('a[href*="wa.me/"]').forEach(link=>{link.href=`https://wa.me/${phone.replace(/\D/g,'')}`});
  if(!document.querySelector('.nexa-call-float')){const call=document.createElement('a');call.className='nexa-call-float';call.href=`https://wa.me/${phone.replace(/\D/g,'')}`;call.target='_blank';call.rel='noopener';call.setAttribute('aria-label',`Call or WhatsApp NexaTrade at ${display}`);call.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16.8 13.7c-.3-.1-1.8-.9-2.1-1-.3-.1-.5-.1-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-1.8-.9-3-1.7-4.2-3.8-.3-.5.3-.5.8-1.6.1-.2 0-.4 0-.6-.1-.2-.7-1.7-1-2.3-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.2 1.2-1.2 2.9s1.2 3.3 1.4 3.6c.2.2 2.4 3.7 5.9 5.2 2.2.9 3.1 1 4.2.8.7-.1 2.1-.9 2.4-1.7.3-.8.3-1.5.2-1.7-.2-.2-.4-.3-.7-.4M12 21.8c-1.8 0-3.6-.5-5.1-1.4L1.2 22l1.5-5.5A10 10 0 1 1 12 21.8m0-18.1a8.1 8.1 0 0 0-6.9 12.4l.2.3-.9 3.2 3.3-.9.3.2A8.1 8.1 0 1 0 12 3.7"/></svg><span><small>Call or WhatsApp now</small><b></b></span>';call.querySelector('b').textContent=display;document.body.append(call)}
  if(!document.querySelector('footer')){const footer=document.createElement('footer');footer.className='nexa-global-footer';footer.innerHTML='<div class="nexa-global-footer-grid"><div><strong>NexaTrade</strong><p>Digital-asset portfolio and workflow technology focused on transparent records, customer controls and responsible risk communication.</p></div><div><strong>Support</strong><a href="mailto:support@ainexabot.com">support@ainexabot.com</a><a data-phone></a><a data-whatsapp target="_blank" rel="noopener">WhatsApp support</a></div><div><strong>Legal & safety</strong><a href="terms.html">Terms of Use</a><a href="privacy.html">Privacy Notice</a><a href="risk-disclosure.html">Risk Disclosure</a><a href="custody-consent.html">Custody consent</a></div></div><div class="nexa-global-footer-legal"><b>Important:</b> NexaTrade does not guarantee returns or provide personalized investment advice through this website. Digital assets are volatile and may lose all value. Eligibility, jurisdiction, verification and approved-provider requirements apply.<span>© 2026 NexaTrade. All rights reserved.</span></div>';const phoneLink=footer.querySelector('[data-phone]');phoneLink.href=`tel:${phone}`;phoneLink.textContent=display;const whatsApp=footer.querySelector('[data-whatsapp]');whatsApp.href=`https://wa.me/${phone.replace(/\D/g,'')}`;document.body.append(footer)}
  const consent=()=>localStorage.getItem('nexa-analytics-consent')==='granted';
  const load=(src,attrs={})=>{if(document.querySelector(`script[src="${src}"]`))return;const s=document.createElement('script');s.async=true;s.src=src;Object.entries(attrs).forEach(([k,v])=>s.setAttribute(k,v));document.head.append(s)};
  function loadGoogle(){if(!consent())return;const ga=/^G-[A-Z0-9]+$/.test(c.googleAnalyticsId||'')?c.googleAnalyticsId:null,ads=/^AW-[0-9]+$/.test(c.googleAdsId||'')?c.googleAdsId:null,tag=ga||ads;if(tag){load(`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(tag)}`);window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('consent','default',{analytics_storage:'granted',ad_storage:ads?'granted':'denied',ad_user_data:ads?'granted':'denied',ad_personalization:'denied'});if(ga)window.gtag('config',ga,{anonymize_ip:true,send_page_view:true});if(ads)window.gtag('config',ads)}if(/^ca-pub-[0-9]+$/.test(c.adsenseClient||''))load(`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(c.adsenseClient)}`,{crossorigin:'anonymous'})}
  window.NEXA_ENABLE_GOOGLE_TRACKING=()=>{localStorage.setItem('nexa-analytics-consent','granted');loadGoogle()};window.NEXA_DISABLE_GOOGLE_TRACKING=()=>localStorage.setItem('nexa-analytics-consent','denied');
  if(!localStorage.getItem('nexa-analytics-consent')&&(c.googleAnalyticsId||c.googleAdsId||c.adsenseClient)){const notice=document.createElement('aside');notice.setAttribute('aria-label','Analytics preferences');Object.assign(notice.style,{position:'fixed',zIndex:'9999',left:'16px',right:'16px',bottom:'16px',maxWidth:'620px',margin:'auto',padding:'16px',border:'1px solid rgba(184,205,235,.25)',borderRadius:'10px',background:'#09172a',color:'#eef5ff',boxShadow:'0 16px 50px rgba(0,0,0,.4)',font:'12px Manrope,Arial,sans-serif'});notice.innerHTML='<p style="margin:0 0 12px">We use optional Google Analytics and advertising cookies to measure and improve the website. You can accept or decline these optional cookies.</p><div style="display:flex;gap:8px"><button data-consent="accept" class="button">Accept</button><button data-consent="decline" class="button secondary">Decline</button></div>';notice.querySelector('[data-consent="accept"]').onclick=()=>{window.NEXA_ENABLE_GOOGLE_TRACKING();notice.remove()};notice.querySelector('[data-consent="decline"]').onclick=()=>{window.NEXA_DISABLE_GOOGLE_TRACKING();notice.remove()};document.body.append(notice)}
  document.addEventListener('click',event=>{const link=event.target.closest('a');if(!link||typeof window.gtag!=='function')return;const href=link.getAttribute('href')||'';let eventName='';if(href.startsWith('https://wa.me/'))eventName='contact_whatsapp';else if(href.startsWith('tel:'))eventName='contact_phone';else if(href.includes('course-')||href==='courses.html')eventName='view_course_offer';else if(href==='login.html')eventName='begin_signup_or_login';if(eventName)window.gtag('event',eventName,{link_url:link.href,link_text:(link.textContent||'').trim().slice(0,100),page_path:location.pathname})});
  if('requestIdleCallback'in window)window.requestIdleCallback(loadGoogle,{timeout:2500});else setTimeout(loadGoogle,1500);
})();
