(() => {
  'use strict';
  const c=window.NEXA_SITE||{},phone=c.supportPhoneE164||'+16593002482',display=c.supportPhoneDisplay||'+1 659 300 2482';
  let icon=document.querySelector('link[rel="icon"]');if(!icon){icon=document.createElement('link');icon.rel='icon';icon.type='image/svg+xml';document.head.append(icon)}icon.href='images/logo.svg';
  document.querySelectorAll('.brand-mark').forEach(mark=>{mark.setAttribute('role','img');mark.setAttribute('aria-label','NexaTrade logo');Object.assign(mark.style,{backgroundImage:'url("images/logo.png")',backgroundSize:'cover',backgroundPosition:'center',backgroundRepeat:'no-repeat',clipPath:'none',filter:'none'})});
  document.querySelectorAll('a[href^="tel:"]').forEach(link=>{link.href=`tel:${phone}`;if(!link.classList.contains('call-nav'))link.textContent=display});document.querySelectorAll('a[href*="wa.me/"]').forEach(link=>{link.href=`https://wa.me/${phone.replace(/\D/g,'')}`});
  if(!document.querySelector('.nexa-call-float')){const call=document.createElement('a');call.className='nexa-call-float';call.href=`tel:${phone}`;call.setAttribute('aria-label',`Call NexaTrade at ${display}`);call.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 10.8c1.5 2.9 3.8 5.2 6.7 6.7l2.2-2.2c.3-.3.7-.4 1.1-.3 1.2.4 2.5.6 3.8.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1C10.8 21 3 13.2 3 3.6c0-.6.4-1 1-1h3.5c.6 0 1 .4 1 1 0 1.3.2 2.6.6 3.8.1.4 0 .8-.3 1.1l-2.2 2.3z"/></svg><span><small>Call now</small><b></b></span>';call.querySelector('b').textContent=display;document.body.append(call)}
  if(!document.querySelector('footer')){const footer=document.createElement('footer');footer.className='nexa-global-footer';footer.innerHTML='<div class="nexa-global-footer-grid"><div><strong>NexaTrade</strong><p>Digital-asset portfolio and workflow technology focused on transparent records, customer controls and responsible risk communication.</p></div><div><strong>Support</strong><a href="mailto:support@ainexabot.com">support@ainexabot.com</a><a data-phone></a><a data-whatsapp target="_blank" rel="noopener">WhatsApp support</a></div><div><strong>Legal & safety</strong><a href="terms.html">Terms of Use</a><a href="privacy.html">Privacy Notice</a><a href="risk-disclosure.html">Risk Disclosure</a><a href="custody-consent.html">Custody consent</a></div></div><div class="nexa-global-footer-legal"><b>Important:</b> NexaTrade does not guarantee returns or provide personalized investment advice through this website. Digital assets are volatile and may lose all value. Eligibility, jurisdiction, verification and approved-provider requirements apply.<span>© 2026 NexaTrade. All rights reserved.</span></div>';const phoneLink=footer.querySelector('[data-phone]');phoneLink.href=`tel:${phone}`;phoneLink.textContent=display;const whatsApp=footer.querySelector('[data-whatsapp]');whatsApp.href=`https://wa.me/${phone.replace(/\D/g,'')}`;document.body.append(footer)}
  const consent=()=>localStorage.getItem('nexa-analytics-consent')==='granted';
  const load=(src,attrs={})=>{if(document.querySelector(`script[src="${src}"]`))return;const s=document.createElement('script');s.async=true;s.src=src;Object.entries(attrs).forEach(([k,v])=>s.setAttribute(k,v));document.head.append(s)};
  function loadGoogle(){if(!consent())return;const ga=/^G-[A-Z0-9]+$/.test(c.googleAnalyticsId||'')?c.googleAnalyticsId:null,ads=/^AW-[0-9]+$/.test(c.googleAdsId||'')?c.googleAdsId:null,tag=ga||ads;if(tag){load(`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(tag)}`);window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('consent','default',{analytics_storage:'granted',ad_storage:ads?'granted':'denied',ad_user_data:ads?'granted':'denied',ad_personalization:'denied'});if(ga)window.gtag('config',ga,{anonymize_ip:true,send_page_view:true});if(ads)window.gtag('config',ads)}if(/^ca-pub-[0-9]+$/.test(c.adsenseClient||''))load(`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(c.adsenseClient)}`,{crossorigin:'anonymous'})}
  window.NEXA_ENABLE_GOOGLE_TRACKING=()=>{localStorage.setItem('nexa-analytics-consent','granted');loadGoogle()};window.NEXA_DISABLE_GOOGLE_TRACKING=()=>localStorage.setItem('nexa-analytics-consent','denied');
  if(!localStorage.getItem('nexa-analytics-consent')&&(c.googleAnalyticsId||c.googleAdsId||c.adsenseClient)){const notice=document.createElement('aside');notice.setAttribute('aria-label','Analytics preferences');Object.assign(notice.style,{position:'fixed',zIndex:'9999',left:'16px',right:'16px',bottom:'16px',maxWidth:'620px',margin:'auto',padding:'16px',border:'1px solid rgba(184,205,235,.25)',borderRadius:'10px',background:'#09172a',color:'#eef5ff',boxShadow:'0 16px 50px rgba(0,0,0,.4)',font:'12px Manrope,Arial,sans-serif'});notice.innerHTML='<p style="margin:0 0 12px">We use optional Google Analytics and advertising cookies to measure and improve the website. You can accept or decline these optional cookies.</p><div style="display:flex;gap:8px"><button data-consent="accept" class="button">Accept</button><button data-consent="decline" class="button secondary">Decline</button></div>';notice.querySelector('[data-consent="accept"]').onclick=()=>{window.NEXA_ENABLE_GOOGLE_TRACKING();notice.remove()};notice.querySelector('[data-consent="decline"]').onclick=()=>{window.NEXA_DISABLE_GOOGLE_TRACKING();notice.remove()};document.body.append(notice)}
  if('requestIdleCallback'in window)window.requestIdleCallback(loadGoogle,{timeout:2500});else setTimeout(loadGoogle,1500);
})();
