import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const staffHeader=document.querySelector('.staff-head>div');if(staffHeader&&!staffHeader.querySelector('a[href="articles.html"]')){const learn=document.createElement('a');learn.href='articles.html';learn.textContent='Learning center';staffHeader.insertBefore(learn,staffHeader.querySelector('a'))}
const c=window.NEXA_SUPABASE||{},s=createClient(c.url,c.publishableKey),q=x=>document.querySelector(x),esc=v=>String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));let conversations=[],profiles={},active=null,filter='all';
const auth=await s.auth.getUser(),user=auth.data.user;if(!user)location.replace('staff-login.html');const profile=await s.from('profiles').select('display_name,role').eq('id',user.id).single();if(!['operator','compliance_admin'].includes(profile.data?.role))location.replace('staff-login.html');if(profile.data?.role==='operator'){const access=await s.from('staff_chat_assignments').select('is_available').eq('staff_id',user.id).maybeSingle();if(!access.data?.is_available){await s.auth.signOut();location.replace('staff-login.html')}}q('#staff-name').textContent=profile.data.display_name;
const customerLabel=x=>profiles[x.customer_id]?.display_name||(/visitor/i.test(x.subject||'')?'Website visitor':'Guest customer');
function renderList(){const rows=conversations.filter(x=>filter==='all'||x.status===filter);q('#conversation-list').innerHTML=rows.map(x=>`<button class="conversation-row ${active===x.id?'active':''}" data-chat="${x.id}"><b>${esc(customerLabel(x))}</b><span>${esc(x.subject||'Support conversation')}</span><small>${esc(x.status)} · ${new Date(x.last_message_at||x.created_at).toLocaleString()}</small></button>`).join('')||'<p class="empty-state">No conversations in this queue.</p>';document.querySelectorAll('[data-chat]').forEach(x=>x.onclick=()=>openChat(x.dataset.chat))}
async function load(){const [cs,ps]=await Promise.all([s.from('chat_conversations').select('*').order('last_message_at',{ascending:false}),s.rpc('admin_customer_directory')]);if(cs.error)return;conversations=cs.data||[];profiles=Object.fromEntries((ps.data||[]).map(x=>[x.customer_id,x]));renderList();if(active&&conversations.some(x=>x.id===active))await openChat(active)}
async function openChat(id){active=id;renderList();const conversation=conversations.find(x=>x.id===id),result=await s.from('chat_messages').select('*').eq('conversation_id',id).order('created_at'),assignedName=conversation.assigned_staff?(profiles[conversation.assigned_staff]?.display_name||'Staff member'):null,isMine=conversation.assigned_staff===user.id,isOther=!!conversation.assigned_staff&&!isMine,humanMode=['waiting_for_staff','assigned'].includes(conversation.status);q('#chat-empty').hidden=true;q('#chat-active').hidden=false;q('#chat-customer').textContent=customerLabel(conversation);q('#chat-state').textContent=assignedName?`${conversation.status} · ${assignedName} joined`:conversation.status;q('#claim').textContent=isMine?'Joined':isOther?`${assignedName} joined`:'Claim & join';q('#claim').disabled=isMine||isOther||['resolved','closed'].includes(conversation.status);q('#resolve').disabled=!isMine;q('#reply').disabled=!isMine;q('#staff-reply button').disabled=!isMine;q('#reply').placeholder=isMine?'Write a clear support response. Never request passwords or wallet secrets.':'Claim this conversation before replying.';q('#staff-messages').innerHTML=(result.data||[]).filter(x=>!(humanMode&&x.sender_type==='assistant')).map(x=>`<div class="staff-message ${x.sender_type}">${esc(x.message)}<small>${x.sender_type} · ${new Date(x.created_at).toLocaleString()}</small></div>`).join('');q('#staff-messages').scrollTop=q('#staff-messages').scrollHeight}
q('#staff-reply').onsubmit=async e=>{e.preventDefault();if(!active)return;const message=q('#reply').value.trim(),{error}=await s.rpc('staff_send_chat',{p_conversation_id:active,p_message:message});if(error)return alert(error.message);q('#reply').value='';await load()};q('#claim').onclick=async()=>{if(active){const{error}=await s.rpc('staff_claim_chat',{p_conversation_id:active});if(error)return alert(error.message);await load()}};q('#resolve').onclick=async()=>{if(active&&confirm('Mark this conversation resolved?')){const{error}=await s.rpc('staff_close_chat',{p_conversation_id:active});if(error)return alert(error.message);await load()}};q('#refresh').onclick=load;document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;document.querySelectorAll('[data-filter]').forEach(y=>y.classList.toggle('active',x===y));renderList()});q('#staff-logout').onclick=async()=>{await s.auth.signOut();location.replace('staff-login.html')};await load();setInterval(load,5000);
